extends Node2D
var RoomPos = 0
var RoomInd = 0
var Rodger = preload("res://Scenes/ReRodger.tscn")
var Hack = preload("res://Scenes/Hack.tscn")
var TechnoZen = preload("res://Scenes/TechnoZen.tscn")
var activate = false
var EnemiesCounter = 0
#Пожалуй, пора бросить все к черту и в Кисловодск..
func _ready() -> void:
	while activate == false:
		await get_tree().create_timer(0.1).timeout
	print(RoomInd)
	get_parent().get_node("UwUGG/UwUGG").EPICER_MUSIK()
	var Bodies = get_tree().get_nodes_in_group("Bodies")
	for node in Bodies:
		node.queue_free()
	if RoomInd == 0:
		Global.BodyCountForLib = 0
		$DoorExit.queue_free()
	elif RoomInd == 1:
		EnemiesCounter =3 #U like kissing boys, dont ya? =3
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 254)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 316)
		NewRodger.get_node("Roach").activate()
		Global.BodyCountForLib = 0
	elif RoomInd == 2:
		EnemiesCounter = 4
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 254)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		var NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 0)
		NewHack.get_node("ManHack").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 316)
		NewRodger.get_node("Roach").activate()
	elif RoomInd == 3:
		EnemiesCounter = 5
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 254)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		var NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 0)
		NewHack.get_node("ManHack").activate()
		NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 100)
		NewHack.get_node("ManHack").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 316)
		NewRodger.get_node("Roach").activate()
	elif RoomInd == 4:
		EnemiesCounter = 1
		var NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position  = Vector2(800 + RoomPos, 316)
		NewTechnoZen.get_node("TechnoZen").activate()
	elif RoomInd == 5:
		EnemiesCounter = 4
		var NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position  = Vector2(600 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 316)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		var NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 0)
		NewHack.get_node("ManHack").activate()
	elif RoomInd == 6:
		EnemiesCounter = 5
		var NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(600 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 254)
		NewRodger.get_node("Roach").activate()
		var NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 0)
		NewHack.get_node("ManHack").activate()
		NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 100)
		NewHack.get_node("ManHack").activate()
	elif RoomInd == 7:
		EnemiesCounter = 6
		var NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(600 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(1000 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		NewTechnoZen.get_node("TechnoZen").ASYNC = 2.5
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 316)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		var NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 0)
		NewHack.get_node("ManHack").activate()
		NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 100)
		NewHack.get_node("ManHack").activate()
	elif RoomInd == 8:
		EnemiesCounter = 7
		var NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(600 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(1000 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		NewTechnoZen.get_node("TechnoZen").ASYNC = 2.5
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 316)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		var NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 0)
		NewHack.get_node("ManHack").activate()
		NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 100)
		NewHack.get_node("ManHack").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 254)
		NewRodger.get_node("Roach").activate()
	elif RoomInd == 9:
		EnemiesCounter = 8
		var NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(600 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(1000 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		NewTechnoZen.get_node("TechnoZen").ASYNC = 2.5
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 316)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		var NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 0)
		NewHack.get_node("ManHack").activate()
		NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 100)
		NewHack.get_node("ManHack").activate()
		NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 150)
		NewHack.get_node("ManHack").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 254)
		NewRodger.get_node("Roach").activate()
	elif RoomInd > 9:
		EnemiesCounter = 8
		var NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(600 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		NewTechnoZen = TechnoZen.instantiate()
		get_parent().add_child(NewTechnoZen)
		NewTechnoZen.global_position = Vector2(1000 + RoomPos, 100)
		NewTechnoZen.get_node("TechnoZen").activate()
		NewTechnoZen.get_node("TechnoZen").ASYNC = 2.5
		var NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 316)
		NewRodger.get_node("Roach").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 285)
		NewRodger.get_node("Roach").activate()
		var NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 0)
		NewHack.get_node("ManHack").activate()
		NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 100)
		NewHack.get_node("ManHack").activate()
		NewHack = Hack.instantiate()
		get_parent().add_child(NewHack)
		NewHack.global_position = Vector2(800 + RoomPos, 150)
		NewHack.get_node("ManHack").activate()
		NewRodger = Rodger.instantiate()
		get_parent().add_child(NewRodger)
		NewRodger.global_position = Vector2(800 + RoomPos, 254)
		NewRodger.get_node("Roach").activate()
	while EnemiesCounter > Global.BodyCountForLib:
		await get_tree().create_timer(0.1).timeout
	$DoorExit.queue_free()
	Global.BodyCountForLib = 0
	get_parent().get_node("UwUGG/UwUGG").calm_down()
	if Save.get_value("~NUMBERS~", "BestLibScore", ) < RoomInd:
		Save.set_value("~NUMBERS~", "BestLibScore", RoomInd )
# Called every frame. 'delta' is thev elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass
